"""Write PaddleX pipeline YAMLs that use a SquiddleOCR recognition directory."""
from __future__ import annotations

import importlib.resources
from pathlib import Path
from typing import Any

import yaml

from ..convert.config import load_yaml


DEFAULT_DET_MODEL = "PP-OCRv6_medium_det"


def _patch_text_recognition(node: Any, model_dir: str, model_name: str, engine: str | None, seal: bool = False,
                            det_model: str | None = None) -> int:
    """Recursively replace every non-seal ``TextRecognition`` sub-module config (and the detector beside it)."""
    n = 0
    if isinstance(node, dict):
        for key, val in node.items():
            if key == "TextRecognition" and isinstance(val, dict) and val.get("module_name") == "text_recognition" and not seal:
                val["model_name"] = model_name
                val["model_dir"] = model_dir
                if engine:
                    val["engine"] = engine
                n += 1
            elif key == "TextDetection" and isinstance(val, dict) and val.get("module_name") == "text_detection" \
                    and not seal and det_model:
                val["model_name"] = det_model
                val["model_dir"] = None
            else:
                n += _patch_text_recognition(val, model_dir, model_name, engine,
                                             seal=seal or key == "SealRecognition", det_model=det_model)
    elif isinstance(node, list):
        for item in node:
            n += _patch_text_recognition(item, model_dir, model_name, engine, seal=seal, det_model=det_model)
    return n


def pipeline_template(pipeline: str) -> dict[str, Any]:
    """Load the bundled copy of a PaddleX pipeline config (PaddleX 3.7.2, Apache-2.0)."""
    res = importlib.resources.files("squiddleocr.data").joinpath("pipelines").joinpath(f"{pipeline}.yaml")
    return yaml.safe_load(res.read_text(encoding="utf-8"))


def write_pipeline_config(model_dir: str | Path, output: str | Path, pipeline: str = "PP-StructureV3",
                          engine: str | None = "onnxruntime", det_model: str | None = DEFAULT_DET_MODEL) -> int:
    """Write ``output`` as ``pipeline`` config with all text recognisers pointed at ``model_dir``.

    Only the general OCR recognisers are replaced (the seal recogniser keeps its
    stock model). The text detectors beside them are set to ``det_model``
    (PP-OCRv6 medium by default; ``None`` keeps the template's). Returns the
    number of replaced recognisers.
    """
    model_dir = Path(model_dir).resolve()
    model_name = load_yaml(model_dir / "inference.yml")["Global"]["model_name"]
    cfg = pipeline_template(pipeline)
    n = _patch_text_recognition(cfg, str(model_dir), model_name, engine, det_model=det_model)
    if n == 0:
        raise ValueError(f"No TextRecognition sub-module found in {pipeline} template")
    Path(output).write_text(
        f"# Generated by squiddle pipeline-config from PaddleX's {pipeline}.yaml\n"
        + yaml.safe_dump(cfg, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    return n
